# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cluno' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cluno

  pod 'Kingfisher' # - image downloading and caching

end
